In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import re

In [ ]:
# data loading
# link: https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela
df_1988 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[0].iloc[:,:]
df_1989 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[1].iloc[:,:]
df_1990 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[2].iloc[:,:]
df_1991 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[3].iloc[:,:]
df_1992 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[4].iloc[:,:]
df_1997 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[5].iloc[:,:]
df_2001 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[6].iloc[:,:]
df_2002 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[7].iloc[:,:]
df_2003 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[8].iloc[:,:]
df_2004 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[9].iloc[:,:]
df_2005 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[10].iloc[:,:]
df_2006 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[11].iloc[:,:]
df_2007 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[12].iloc[:,:]
df_2008 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[13].iloc[:,:]
df_2009 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[14].iloc[:,:]
df_2010 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[15].iloc[:,:]
df_2011 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[16].iloc[:,:]
df_2012 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[17].iloc[:,:]
df_2013 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[18].iloc[:,:]
df_2014 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[19].iloc[:,:]
df_2015 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[20].iloc[:,:]
df_2016 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[21].iloc[:,:]
df_2017 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[22].iloc[:,:]
df_2018 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[23].iloc[:,:]
df_2019 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[24].iloc[:,:]
df_2020 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[25].iloc[:,:]
df_2021 = pd.read_html("https://es.wikipedia.org/wiki/Anexo:Historial_de_partidos_de_la_selecci%C3%B3n_de_baloncesto_de_Venezuela", header=0)[26].iloc[:,:]

In [ ]:
df1 = pd.concat([df_1988, df_1989, df_1990, df_2009, df_2014, df_2015,
                df_2016, df_2017, df_2018, df_2019, df_2020,
                df_2021], axis=0)
df1 = df1.reset_index()
df1 = df1.drop(['index','#','Unnamed: 4','Unnamed: 6','Unnamed: 3',
                'Unnamed: 5'], axis=1)
df1.head(10)

,Fecha,Lugar,Local,Resultado,Visitante,Competición
0,22 de mayo de 1988,Montevideo,Uruguay,100:67,Venezuela,Pre-Olímpico 1988
1,23 de mayo de 1988,Montevideo,Canada,94:88,Venezuela,Pre-Olímpico 1988
2,24 de mayo de 1988,Montevideo,Argentina,110:77,Venezuela,Pre-Olímpico 1988
3,25 de mayo de 1988,Montevideo,Brasil,91:83,Venezuela,Pre-Olímpico 1988
4,26 de mayo de 1988,Montevideo,Puerto Rico,65:63,Venezuela,Pre-Olímpico 1988
5,28 de mayo de 1988,Montevideo,Mexico,110:93,Venezuela,Pre-Olímpico 1988
6,8 de junio de 1989,Ciudad de México,Venezuela,99:78,Canada,Pre-Mundial 1989
7,9 de junio de 1989,Ciudad de México,Venezuela,110:89,Ecuador,Pre-Mundial 1989
8,10 de junio de 1988,Ciudad de México,Brasil,131:99,Venezuela,Pre-Mundial 1989
9,11 de junio de 1989,Ciudad de México,Venezuela,130:106,Argentina,Pre-Mundial 1989

In [ ]:
print("The dataset until now has {} rows and {} cols.".format(df1.shape[0],
                                                              df1.shape[1]))

The dataset until now has 148 rows and 6 cols.

In [ ]:
df1 = df1.replace(to_replace="República Dominicana", value="Rep. Dominicana")
df1 = df1.replace(to_replace="Combinado Jugadores Estadounidenses", 
                  value="Estados Unidos")
df1.head(100)

,Fecha,Lugar,Local,Resultado,Visitante,Competición
0,22 de mayo de 1988,Montevideo,Uruguay,100:67,Venezuela,Pre-Olímpico 1988
1,23 de mayo de 1988,Montevideo,Canada,94:88,Venezuela,Pre-Olímpico 1988
2,24 de mayo de 1988,Montevideo,Argentina,110:77,Venezuela,Pre-Olímpico 1988
3,25 de mayo de 1988,Montevideo,Brasil,91:83,Venezuela,Pre-Olímpico 1988
4,26 de mayo de 1988,Montevideo,Puerto Rico,65:63,Venezuela,Pre-Olímpico 1988
...,...,...,...,...,...,...
95,25 de julio de 2016,Valladolid,España,91:55,Venezuela,Amistoso
96,29 de julio de 2016,Chicago,Estados Unidos,80:45,Venezuela,Amistoso
97,6 de agosto de 2016,Río de Janeiro,Venezuela,62:86,Serbia,Juegos Olímpicos
98,8 de agosto de 2016,Río de Janeiro,Estados Unidos,113:69,Venezuela,Juegos Olímpicos
99,10 de agosto de 2016,Río de Janeiro,Venezuela,72:68,China,Juegos Olímpicos

In [ ]:
df1 = df1.rename(columns={"Competición": "Competition",
                        "Fecha": "Date",
                        "Lugar": "Place",
                        "Resultado": "Score",
                        "Visitante": "Visitor"})
df1.head(10)

,Date,Place,Local,Score,Visitor,Competition
0,22 de mayo de 1988,Montevideo,Uruguay,100:67,Venezuela,Pre-Olímpico 1988
1,23 de mayo de 1988,Montevideo,Canada,94:88,Venezuela,Pre-Olímpico 1988
2,24 de mayo de 1988,Montevideo,Argentina,110:77,Venezuela,Pre-Olímpico 1988
3,25 de mayo de 1988,Montevideo,Brasil,91:83,Venezuela,Pre-Olímpico 1988
4,26 de mayo de 1988,Montevideo,Puerto Rico,65:63,Venezuela,Pre-Olímpico 1988
5,28 de mayo de 1988,Montevideo,Mexico,110:93,Venezuela,Pre-Olímpico 1988
6,8 de junio de 1989,Ciudad de México,Venezuela,99:78,Canada,Pre-Mundial 1989
7,9 de junio de 1989,Ciudad de México,Venezuela,110:89,Ecuador,Pre-Mundial 1989
8,10 de junio de 1988,Ciudad de México,Brasil,131:99,Venezuela,Pre-Mundial 1989
9,11 de junio de 1989,Ciudad de México,Venezuela,130:106,Argentina,Pre-Mundial 1989

In [ ]:
df1["L_Score"] = df1['Score'].astype(str)
df1["V_Score"] = df1['Score'].astype(str)

df1["L_Score"] = df1["Score"].str.split(':', 1).str[0].str.strip()
df1["V_Score"] = df1['Score'].str.split(':', 1).str[1].str.strip()

In [ ]:
# cols = list(df1.columns.values)
# cols
df1 = df1[['Date','Place','Local','L_Score','V_Score','Visitor','Competition']]
df1.head(15)

,Date,Place,Local,L_Score,V_Score,Visitor,Competition
0,22 de mayo de 1988,Montevideo,Uruguay,100,67,Venezuela,Pre-Olímpico 1988
1,23 de mayo de 1988,Montevideo,Canada,94,88,Venezuela,Pre-Olímpico 1988
2,24 de mayo de 1988,Montevideo,Argentina,110,77,Venezuela,Pre-Olímpico 1988
3,25 de mayo de 1988,Montevideo,Brasil,91,83,Venezuela,Pre-Olímpico 1988
4,26 de mayo de 1988,Montevideo,Puerto Rico,65,63,Venezuela,Pre-Olímpico 1988
5,28 de mayo de 1988,Montevideo,Mexico,110,93,Venezuela,Pre-Olímpico 1988
6,8 de junio de 1989,Ciudad de México,Venezuela,99,78,Canada,Pre-Mundial 1989
7,9 de junio de 1989,Ciudad de México,Venezuela,110,89,Ecuador,Pre-Mundial 1989
8,10 de junio de 1988,Ciudad de México,Brasil,131,99,Venezuela,Pre-Mundial 1989
9,11 de junio de 1989,Ciudad de México,Venezuela,130,106,Argentina,Pre-Mundial 1989
10,12 de junio de 1989,Ciudad de México,Venezuela,111,84,Paraguay,Pre-Mundial 1989
11,14 de junio de 1989,Ciudad de México,Venezuela,109,102,Rep. Dominicana,Pre-Mundial 1989
12,17 de junio de 1988,Ciudad de México,Puerto Rico,94,91,Venezuela,Pre-Mundial 1989
13,18 de junio de 1988,Ciudad de México,Brasil,158,124,Venezuela,Pre-Mundial 1989
14,14 de julio de 1990,A Coruña,España,96,75,Venezuela,Amistoso

In [ ]:
# The data from these years has different score format, we'll do another df
df2 = pd.concat([df_1991, df_1992, df_1997, df_2001, df_2002,
                 df_2003, df_2004, df_2005, df_2006, df_2007,
                 df_2008, df_2011, df_2012, df_2013], axis=0)
df2 = df2.reset_index()

# Let's rename this column and then merge with the rest of the dataframe
df_2010 = df_2010.rename(columns={"Competición'": "Competición"})

df2 = pd.concat([df2, df_2010], axis=0)
df2 = df2.reset_index(drop=True)
df2 = df2.drop(['index', '#'], axis=1)

In [ ]:
df2 = df2.rename(columns={"Competición": "Competition",
                        "Fecha": "Date",
                        "Lugar": "Place",
                        "Resultado": "L_Score",
                        "Resultado.1": "V_Score",
                        "Visitante": "Visitor"})
df2.head(10)

,Date,Place,Local,L_Score,V_Score,Visitor,Competition
0,16 de mayo de 1991,Valencia,Venezuela,103,59,Paraguay,Suramericano Valencia 91
1,17 de mayo de 1991,Valencia,Venezuela,93,80,Uruguay,Suramericano Valencia 91
2,18 de mayo de 1991,Valencia,Venezuela,87,65,Colombia,Suramericano Valencia 91
3,19 de mayo de 1991,Valencia,Argentina,91,83,Venezuela,Suramericano Valencia 91
4,20 de mayo de 1991,Valencia,Venezuela,102,57,Ecuador,Suramericano Valencia 91
5,21 de mayo de 1991,Valencia,Venezuela,96,89,Brasil,Suramericano Valencia 91
6,22 de mayo de 1991,Valencia,Venezuela,108,45,Perú,Suramericano Valencia 91
7,26 de mayo de 1991,Valencia,Venezuela,122,121,Brasil,Suramericano Valencia 91
8,27 de junio de 1992,Portland,Venezuela,110,92,Uruguay,Pre-Olímpico 1992
9,28 de junio de 1992,Portland,Brasil,128,81,Venezuela,Pre-Olímpico 1992

In [ ]:
df2 = df2.replace(to_replace="Islas Vírgenes Estadounidenses", 
                  value="Islas Vírgenes")

In [ ]:
# Let's join everything and see the dimensions
df = pd.concat([df1, df2], axis=0)
print("The dataset until now has {} rows and {} cols.".format(df.shape[0],
                                                              df.shape[1]))

The dataset until now has 351 rows and 7 cols.

In [ ]:
# We'll create columns to record Venezuela's team wins and losses
df["Win"] = 0
df["Loss"] = 0

results = np.where(
    ((df['Visitor'] == 'Venezuela') & (df['V_Score'] > df['L_Score'])) |
    ((df['Local'] == 'Venezuela') & (df['L_Score'] > df['V_Score'])),
    'win', 'loss')

# We can quickly check the team's record (count of total wins and losses)
record = {'wins': np.sum(results == 'win'), 'losses': np.sum(results == 'loss')}
record

{'wins': 183, 'losses': 168}

In [ ]:
df["Local"] = df["Local"].str.strip()
df["Visitor"] = df["Visitor"].str.strip()

df["V_Score"] = pd.to_numeric(df["V_Score"], downcast="integer")
df["L_Score"] = pd.to_numeric(df["L_Score"], downcast="integer")

# Setting 1 for wins and 0 for losses according to the resulting score 
def get_results(df):
  for row in df:
    if ((df['Visitor'] == 'Venezuela') & (df['V_Score'] > df['L_Score'])):
      df["Win"] = 1
    elif ((df['Local'] == 'Venezuela') & (df['L_Score'] > df['V_Score'])):
      df["Win"] = 1
    else: 
      df["Loss"] = 1
  return df

df = df.apply(get_results, axis='columns')

In [ ]:
df = df.reset_index(drop=True)
df.head(10)

,Date,Place,Local,L_Score,V_Score,Visitor,Competition,Win,Loss
0,22 de mayo de 1988,Montevideo,Uruguay,100,67,Venezuela,Pre-Olímpico 1988,0,1
1,23 de mayo de 1988,Montevideo,Canada,94,88,Venezuela,Pre-Olímpico 1988,0,1
2,24 de mayo de 1988,Montevideo,Argentina,110,77,Venezuela,Pre-Olímpico 1988,0,1
3,25 de mayo de 1988,Montevideo,Brasil,91,83,Venezuela,Pre-Olímpico 1988,0,1
4,26 de mayo de 1988,Montevideo,Puerto Rico,65,63,Venezuela,Pre-Olímpico 1988,0,1
5,28 de mayo de 1988,Montevideo,Mexico,110,93,Venezuela,Pre-Olímpico 1988,0,1
6,8 de junio de 1989,Ciudad de México,Venezuela,99,78,Canada,Pre-Mundial 1989,1,0
7,9 de junio de 1989,Ciudad de México,Venezuela,110,89,Ecuador,Pre-Mundial 1989,1,0
8,10 de junio de 1988,Ciudad de México,Brasil,131,99,Venezuela,Pre-Mundial 1989,0,1
9,11 de junio de 1989,Ciudad de México,Venezuela,130,106,Argentina,Pre-Mundial 1989,1,0

In [ ]:
# Formatting date
df['Date'] = df['Date'].str.replace(' de ','')

# Months
df['Date'] = df['Date'].str.replace('enero','01')
df['Date'] = df['Date'].str.replace('febrero','02')
df['Date'] = df['Date'].str.replace('marzo','03')
df['Date'] = df['Date'].str.replace('abril','04')
df['Date'] = df['Date'].str.replace('mayo','05')
df['Date'] = df['Date'].str.replace('junio','06')
df['Date'] = df['Date'].str.replace('julio','07')
df['Date'] = df['Date'].str.replace('agosto','08')
df['Date'] = df['Date'].str.replace('septiembre','09')
df['Date'] = df['Date'].str.replace('octubre','10')
df['Date'] = df['Date'].str.replace('noviembre','11')
df['Date'] = df['Date'].str.replace('diciembre','12')

# Days
def format_day(df):
  for row in df:
    if len(df["Date"]) == 7:
      df["Date"] = '0' + df["Date"]
  return df

df = df.apply(format_day, axis='columns')
df

,Date,Place,Local,L_Score,V_Score,Visitor,Competition,Win,Loss
0,22051988,Montevideo,Uruguay,100,67,Venezuela,Pre-Olímpico 1988,0,1
1,23051988,Montevideo,Canada,94,88,Venezuela,Pre-Olímpico 1988,0,1
2,24051988,Montevideo,Argentina,110,77,Venezuela,Pre-Olímpico 1988,0,1
3,25051988,Montevideo,Brasil,91,83,Venezuela,Pre-Olímpico 1988,0,1
4,26051988,Montevideo,Puerto Rico,65,63,Venezuela,Pre-Olímpico 1988,0,1
...,...,...,...,...,...,...,...,...,...
346,28072010,Neiva,Venezuela,104,42,Ecuador,Sudamericano 2010,1,0
347,30072010,Neiva,Venezuela,67,79,Brasil,Sudamericano 2010,0,1
348,31072010,Neiva,Venezuela,70,76,Uruguay,Sudamericano 2010,0,1
349,07082010,Brasilia,Venezuela,50,92,Brasil,Super 4,0,1
350,08082010,Brasilia,Venezuela,75,50,Chile,Super 4,1,0

In [ ]:
# There are only two rows with missing data (day of the game), index 128
# and 237, let's drop them since I could not find the info about those games..
df = df.drop([df.index[128],df.index[237]])

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d%m%Y', utc=False)
df['Date'] = df['Date'].dt.date
df

,Date,Place,Local,L_Score,V_Score,Visitor,Competition,Win,Loss
0,1988-05-22,Montevideo,Uruguay,100,67,Venezuela,Pre-Olímpico 1988,0,1
1,1988-05-23,Montevideo,Canada,94,88,Venezuela,Pre-Olímpico 1988,0,1
2,1988-05-24,Montevideo,Argentina,110,77,Venezuela,Pre-Olímpico 1988,0,1
3,1988-05-25,Montevideo,Brasil,91,83,Venezuela,Pre-Olímpico 1988,0,1
4,1988-05-26,Montevideo,Puerto Rico,65,63,Venezuela,Pre-Olímpico 1988,0,1
...,...,...,...,...,...,...,...,...,...
346,2010-07-28,Neiva,Venezuela,104,42,Ecuador,Sudamericano 2010,1,0
347,2010-07-30,Neiva,Venezuela,67,79,Brasil,Sudamericano 2010,0,1
348,2010-07-31,Neiva,Venezuela,70,76,Uruguay,Sudamericano 2010,0,1
349,2010-08-07,Brasilia,Venezuela,50,92,Brasil,Super 4,0,1
350,2010-08-08,Brasilia,Venezuela,75,50,Chile,Super 4,1,0

In [ ]:
df = df.sort_values(by="Date", axis=0, ascending=True)
df = df.reset_index(drop=True)
df

,Date,Place,Local,L_Score,V_Score,Visitor,Competition,Win,Loss
0,1988-05-22,Montevideo,Uruguay,100,67,Venezuela,Pre-Olímpico 1988,0,1
1,1988-05-23,Montevideo,Canada,94,88,Venezuela,Pre-Olímpico 1988,0,1
2,1988-05-24,Montevideo,Argentina,110,77,Venezuela,Pre-Olímpico 1988,0,1
3,1988-05-25,Montevideo,Brasil,91,83,Venezuela,Pre-Olímpico 1988,0,1
4,1988-05-26,Montevideo,Puerto Rico,65,63,Venezuela,Pre-Olímpico 1988,0,1
...,...,...,...,...,...,...,...,...,...
344,2021-06-29,Kaunas,Lituania,76,65,Venezuela,Torneo Preolímpico FIBA 2020,0,1
345,2021-06-30,Kaunas,Venezuela,94,80,Corea del Sur,Torneo Preolímpico FIBA 2020,1,0
346,2021-07-03,Kaunas,Eslovenia,98,70,Venezuela,Torneo Preolímpico FIBA 2020,0,1
347,2021-11-26,Buenos Aires,Venezuela,77,56,Panamá,Eliminatorias al Mundial 2023,1,0
348,2021-11-27,Buenos Aires,Panamá,53,71,Venezuela,Eliminatorias al Mundial 2023,1,0

In [ ]:
# At this point the dataset has been both cleaned and formatted, now we can 
# export this to Excel. Further analysis will be conducted in Tableau.
df.to_excel(r'/content/drive/MyDrive/Colab Notebooks/Python for Data Science/Venezuela_Basket_Data.xlsx', index = False)

In [ ]:
# Here is the link for the Tableau story created for this particular project:
# https://public.tableau.com/app/profile/harold.harting/viz/VenezuelasNationalBasketballTeamInsights/VenezuelasNationalBasketballTeamInsights?publish=yes